### ISSUE TITLE
Custom validation

### ISSUE THREAD

**Issue by avechuche** [runceel/ReactiveProperty#285]
Hello, first of all, thank you for this wonderful package.

I have a "problem" when enabling / disabling a button in the UI.

This is a piece of code that works properly.

```
[Required(ErrorMessage = @"Required property")]
public ReactiveProperty<string> NameOne { get; }

public AsyncReactiveCommand AsyncSaveCommand => new[]
	{
		NameOne.ObserveHasErrors.Inverse()
	}
	.CombineLatest(x => x.Any(_ => _))
	.ToAsyncReactiveCommand()
	.WithSubscribe(async () =>
	{
		await ...
	});
```

But I would like to add some validation and I don't know how to do it. Ex.

```
public ReactiveProperty<MyCustomDTO> CustomDTO { get; set; } = new();

public ReactiveCollection<MyCustomDTO> ListOfMyCustomDTO { get; } = new();

public AsyncReactiveCommand AsyncSaveCommand => new[]
	{
                //ListOfMyCustomDTO.Any(),
                //CustomDTO => Some validation with some CustomDTO property. For now only verify if is null
		NameOne.ObserveHasErrors.Inverse()
	}
	.CombineLatest(x => x.Any(_ => _))
	.ToAsyncReactiveCommand()
	.WithSubscribe(async () =>
	{
		await ...
	});

ListOfMyCustomDTO is binding with ListBox

CustomDTO is binding with ComboBox SelectItem
```

Thx!

**Comment by soi013** [comment]
I have made three changes to the code you provided. Does this serve your purpose?



### ReactiveCollection IsAny as Observable

Create a stream of ReactiveCollections whose count is greater than 0.

```csharp
ListOfMyCustomDTO.ObserveProperty(x => x.Count).Select(x => x > 0).DistinctUntilChanged();
````



### Subscribe to changes in `CustomDTO.Value` and its property.

Subscribe to changes in `CustomDTO.Value` and its properties in `MyCustomDTO` (`IsValidMyCustomDTO`) due to Combobox selection changes.

Using the nested ` ObserveProperty()`, you can do both at the same time.

````csharp
CustomDTO.ObserveProperty(x => x.Value.IsValidMyCustomDTO)
````



### Eliminate property initialization with `=>`.

It is not your question, but there is a part of the sample code should be changed.

The expression-bodied-property(`prop => ... `), you shouldn't do anything complicated with the initialization. Every time you `get` a property, the initialization process will be executed.

Instead, initialize it in the constructor.

https://docs.microsoft.com/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members#read-only-properties



### Summary

Finally, here is the code that summarizes the three changes.

```csharp
public ReactiveProperty<MyCustomDTO> CustomDTO { get; } = new();

public ReactiveCollection<MyCustomDTO> ListOfMyCustomDTO { get; } = new();

public AsyncReactiveCommand AsyncSaveCommand { get; }

public MyViewModel()
{
    AsyncSaveCommand = new[]
	{
        ListOfMyCustomDTO.ObserveProperty(x => x.Count).Select(x => x > 0).DistinctUntilChanged(),
        CustomDTO.ObserveProperty(x => x.Value.IsValidMyCustomDTO),
		NameOne.ObserveHasErrors.Inverse()
	}
	.CombineLatestValuesAreAllTrue()
	.ToAsyncReactiveCommand()
	.WithSubscribe(async () =>
	{
		await ...
	});
}
````



I hope this helps.

**Comment by avechuche** [comment]
@soi013 Hi, thanks for the help. I already solved part of the problem, but I still have one. 

I use the following code 

```
public ReactiveProperty<MyCustomDTO> CustomDTO { get; } = new();

public ReactiveCollection<MyCustomDTO> ListOfMyCustomDTO { get; } = new();

public AsyncReactiveCommand AsyncSaveCommand { get; }

public MyViewModel()
{
    AsyncSaveCommand = new[]
	{
        ListOfMyCustomDTO.ObserveProperty(x => x.Count).Select(x => x > 0).DistinctUntilChanged(),
        CustomDTO.ObserveProperty(x => x.Value != null),
	NameOne.ObserveHasErrors.Inverse()
	}
	.CombineLatestValuesAreAllTrue()
	.ToAsyncReactiveCommand()
	.WithSubscribe(async () =>
	{
		await ...
	});
}
```

This line ``` CustomDTO.ObserveProperty(x => x.Value != null) ``` throw follow ex:

```
Value does not fall within the expected range

StackTrace	"   en Reactive.Bindings.Internals.ExpressionTreeUtils.IsNestedPropertyPath[TSubject,TProperty](Expression`1 propertySelector)\r\n   en Reactive.Bindings.Extensions.INotifyPropertyChangedExtensions.ObserveProperty[TSubject,TProperty](TSubject subject, Expression`1 propertySelector, Boolean isPushCurrentValueAtFirst)
```

**Comment by soi013** [comment]
ObserveProperty can only recieve property-selector.
So, you should use 'CustomDTO.ObserveProperty(x => x.Value).Where(x=> x!= null)'.

**Comment by avechuche** [comment]
Thanks! I already solved the problem!
