### ISSUE TITLE
Thinking on IDisposables

### ISSUE THREAD

**Issue by worldbeater** [runceel/ReactiveProperty#63]
Having a little misunderstanding on how do disposables work with reactive properties. Should we make **each our ViewModel** implement IDisposable interface and should we call .Dispose() method **for each** of our ReactiveProperties declared and used in our code? Or should we do it only in complicated scenarios when we want to stop observing events manually?

According to [this page](https://runceel.github.io/ReactiveProperty/features/ReactiveProperty/#unsubscribe) we should dispose our observables only if we create a subscription loop that should be stopped when ViewModel is no longer needed. 

It would be nice if you could point out best practices on using IDisposables, cases when calling .Dispose() is necessary and when isn't, problems that may arise if we don't stop active subscriptions :)

Thanks, @runceel!

**Comment by runceel** [comment]
Hi,

In this case, you should call Dispose().

```cs
class SomeModel : INotifyPropertyChanged
{
   public string Name { ... }
}

class MyViewModel
{
    public ReactiveProperty Name { get; }
    
    public MyViewModel(SomeModel model)
    {
        Name = model.ObserveProperty(x => x.Name).ToReactiveProperty();
    }
}
```

Because, in this code, SomeModel instance have a MyViewModel instance reference. It is not WeakReference. If MyViewModel instance is created an only one instance, then it is not problem. If MyViewModel instance is created many time, then it is problem. 

Memory leak is occured. Because the MyViewModel instance don't collect by GC.

In this case, you should call Dispose().

**Comment by worldbeater** [comment]
Thanks for detailed explanation! 👍
