### ISSUE TITLE
Creating ReactiveCommands from Non-UI-Observables

### ISSUE THREAD

**Issue by kryppel** [runceel/ReactiveProperty#66]
When using ToReactiveCommand on a non-UI-Observable an InvalidOperationException is thrown since the Command may only be invalidated by the Dispatcher. 

Using ObserveOnDispatcher() on the observable solves this issue, but the commands would be easier to use if ToReactiveCommand(..) would do this internally

**Comment by runceel** [comment]
@kryppel 
Thank you for requesting the feature.
ObserveOnUIDispatcher() has an issue using with the UWP platform.

UWP platform has more than one UI threads when show multi-window.
I think that if call the method internally, then library user can't fix the issue.


Detail is following:
ObserveOnUIDispatcher() use the instance of static field, it means that it can't handle multiple UI threads case.

So that, I think that current implementation is a better way than calling this method internally.
