### ISSUE TITLE
ReactiveProperty doesn't notify on conversion errors

### ISSUE THREAD

**Issue by Vedaevolution** [runceel/ReactiveProperty#76]
Dear Developers,

i have another problem with reactive property. 
When i define a property this way:

`var rp = new ReactiveProperty<int>(100);`
`rp.ObserveHasErrors.Subscribe(...)`

The problem is that the observable doesn't inform me about conversion errors. If i bind rp to a textbox and enter "5Test" it obviously shows a convert error (in the ui) because "5Test" is no integer. Those errors are not sent to ObserveHasErrors observable as it seems. 

Is this intended or an error?

**Comment by runceel** [comment]
@Vedaevolution
This is by design of WPF.
If you want to detect this error, then I think that you should handle the Validation.Error attached event.
https://msdn.microsoft.com/en-us/library/system.windows.controls.validation.error(v=vs.110).aspx

But in this case, I usual use string type in ViewModel layer.
And I create custom validation rule using System.ComponentModel.DataAnnotations.

**Comment by runceel** [comment]
@Vedaevolution 
Because no response one week, I close this issue.
If you have an issue which depends on this, then please re-open this.

Thank you.
