### ISSUE TITLE
Does CanExcute of ReactiveCommand raise on DefaultSceduler?

### ISSUE THREAD

**Issue by soi013** [runceel/ReactiveProperty#83]
Hi,

I have this question.
I think CanExcute of (Async)ReactiveCommand raise on DefaultSceduler.
Is it correct?

---
In source code, it look raising on DefaultSceduler.

```ReactiveCommand.cs
public ReactiveCommand(IObservable<bool> canExecuteSource, IScheduler scheduler, bool initialValue = true)
{
    this.IsCanExecute = initialValue;
    this.Scheduler = scheduler;
    this.CanExecuteSubscription = canExecuteSource
        .DistinctUntilChanged()
        .ObserveOn(scheduler)
        .Subscribe(b =>
        {
            IsCanExecute = b;
            this.CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        });
}
```

---

In Documentation, it dose not look raising on DefaultSceduler.

_ReactiveProperty raise PropertyChanged event on UI thread automaticaly._ 

---

In my demo code, if CanExecute source is changed from other thread, System.InvalidOperationException is cause.

```MainWindowViewModel.cs
DoSomeAsyncCommand = Name
    .Throttle(TimeSpan.FromSeconds(1))
    .Select(x => x.Length >= 5)
    .ToAsyncReactiveCommand();
```

**Comment by runceel** [comment]
I added threading section on the documentation.
https://runceel.github.io/ReactiveProperty/features/Commanding/

> Uhm... I think it's confusing.
I think so too. 
The implementer of AsyncReactiveCommand is @neuecc.
I think that the reason of he didn't implement is performance.
And then I think that it is better way, because automatic switching thread feature is occurred errors on the multi UI thread platform like as UWP.

**Comment by soi013** [comment]
OK, I understand.
Thank you for updating documentation.

Yes, performance is important.
